local textbox = require "in.textbox"

function init(self)
	textbox.acquire()
	textbox.register("login/button", "login/label")
	textbox.register("password/button", "password/label", true)
end

function final(self)
	textbox.unregister()
end

function on_input(self, action_id, action)
	textbox.on_input(action_id, action)
end

function on_reload(self)
	-- Add input-handling code here
	-- Remove this function if not needed
end
