local WIDTH = tonumber(sys.get_config("display.width"))
local HEIGHT = tonumber(sys.get_config("display.height"))

local function random_pos()
	return vmath.vector3(math.random(WIDTH * 2), math.random(HEIGHT * 2), math.random(-100, 100) / 100)
end

function init(self)
	math.randomseed(socket.gettime())
	for i=1,200 do
		factory.create("#bluefactory", random_pos())
	end
	for i=1,20 do
		factory.create("#greenfactory", random_pos())
	end
	for i=1,30 do
		factory.create("#checkpointfactory", random_pos())
	end
end
