local function prettify(t, indentation)
	indentation = indentation or ""
	local s = ""
	for k,v in pairs(t) do
		if type(v) == "table" then
			s = s .. ("%s%s = {\n%s},\n"):format(indentation, k, prettify(v, indentation .. "  "))
		else
			s = s .. ("%s%s = %s,\n"):format(indentation, k, tostring(v))
		end
	end
	return s
end

function on_message(self, message_id, message, sender)
	if message_id == hash("on_gesture") then
		label.set_text("#label", prettify(message))
	end
end
